url: http://sacha.me
permalink: :categories/:title/
description: "Sacha Schmid is a front-end developer from Switzerland, designing and building websites for private clients and small companies using modern HTML, CSS and JavaScript."

timezone: Europe/Zurich

links:
  - title: Home
    url: /
    icon_class: home
  - title: Projects
    url: /projects/
    icon_class: case
  - title: Articles
    url: /articles/
    icon_class: archive
  - title: About
    url: /about/
    icon_class: person

markdown: kramdown
highlighter: pygments

gems:
  - jekyll-sitemap

kramdown:
  enable_coderay: false
  header_offset: 2

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: articles
    values:
      navigation_match: /articles/
  -
    scope:
      path: articles
      type: posts
    values:
      layout: post
  -
    scope:
      path: projects
    values:
      navigation_match: /projects/
  -
    scope:
      path: projects
      type: posts
    values:
      layout: project

exclude: [ 'gulpfile.js', 'package.json', 'LICENSE.md', 'README.md' ]