url: http://sacha.me
permalink: :categories/:title/

timezone: Europe/Zurich

links:
  - title: Home
    url: /
    icon_class: home
  - title: Projects
    url: /projects
    icon_class: case
  - title: Articles
    url: /articles
    icon_class: archive
  - title: About
    url: /about
    icon_class: person

markdown: kramdown
highlighter: pygments

kramdown:
  enable_coderay: false
  header_offset: 2

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "articles"
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      layout: project